version: "3.8"

# https://github.com/bitnami/bitnami-docker-spark
services:
    master:
        image: bitnami/spark:3.0.0-debian-10-r43
        hostname: master
        restart: unless-stopped
        networks:
            - lambda-network
        ports:
            - target: 8080
              published: 8080
        environment:
            SPARK_MODE: "master"
            SPARK_RPC_AUTHENTICATION_ENABLED: "no"
            SPARK_RPC_ENCRYPTION_ENABLED: "no"
            SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
            SPARK_SSL_ENABLED: "no"
            SPARK_PUBLIC_DNS: ${HOST_IP:?err} # Docker host IP
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]  # No need to be on the manager (node.hostname == ???)
                
    worker:
        image: bitnami/spark:3.0.0-debian-10-r43
        hostname: worker
        restart: unless-stopped
        networks:
            - lambda-network
        ports:
            - "8070-8079:8070-8079"
        environment:
            SPARK_MODE: "worker"
            SPARK_MASTER_URL: "spark://master:7077"
            SPARK_WORKER_MEMORY: "8G"
            SPARK_WORKER_CORES: "1"
            SPARK_RPC_AUTHENTICATION_ENABLED: "no"
            SPARK_RPC_ENCRYPTION_ENABLED: "no"
            SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
            SPARK_SSL_ENABLED: "no"
            SPARK_PUBLIC_DNS: ${HOST_IP:?err} # Docker host IP
        deploy:
            mode: replicated
            replicas: 1                           
  
networks:
    lambda-network:
        name: lambda-network
