{
 "title": "Loomo",
 "time": { "from": "2021-05-13T03:17:47.688Z", "to": "2021-05-13T03:17:47.691Z" },
 "templating": {
  "list": [
   {
    "name": "senderName",
    "label": "Sender Name",
    "query": "Data01, Data02, loomo54age18gl20623"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "find3Streaming, find3Streaming-test"
   },
   { "name": "odomTime", "label": "Odometry TIme", "query": "1" },
   { "name": "odomUnit", "label": "Time Unit", "query": "MINUTE, HOUR, DAY, MONTHS" },
   { "name": "odomStep", "label": "Odometry Steps", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Loomo path over Time",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "query": "SELECT  __time, positionX, positionY, senderName\nFROM \"${source}-odomClean\"\nWHERE senderName='${senderName}' AND __time >= CURRENT_TIMESTAMP - INTERVAL '${odomTime}'  ${odomUnit}",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT  __time, positionX, positionY, senderName\\nFROM \\\"${source}-odomClean\\\"\\nWHERE senderName='${senderName}' AND __time >= CURRENT_TIMESTAMP - INTERVAL '${odomTime}'  ${odomUnit}\",\"queryType\":\"sql\"},\"settings\":{\"contextParameters\":[],\"format\":\"long\"}}",
     "settings": {
      "contextParameters": [],
      "format": "long"
     }
    }
   ]
  },
  {
   "title": "Loomo Path over Steps",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "builder": {
      "query": "SELECT  __time, positionX, positionY, senderName\nFROM \"${source}-odomClean\"\nWHERE senderName='${senderName}' AND __time >= CURRENT_TIMESTAMP - INTERVAL '1' DAY\nORDER BY __time desc\nLIMIT ${odomStep}",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT  __time, positionX, positionY, senderName\\nFROM \\\"${source}-odomClean\\\"\\nWHERE senderName='${senderName}' AND __time >= CURRENT_TIMESTAMP - INTERVAL '1' DAY\\nORDER BY __time desc\\nLIMIT ${odomStep}\",\"queryType\":\"sql\"},\"settings\":{\"contextParameters\":[],\"format\":\"long\"}}",
     "settings": {
      "contextParameters": [],
      "format": "long"
     }
    }
   ]
  },
  {
   "title": "Odometry Distance",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "builder": {
      "query": "SELECT __time, senderName, \"aggdistancelocal$(secs, nsecs, x, y, z)\" AS Distance\nFROM \"${source}-odomDist\"\nWHERE senderName='${senderName}'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT __time, senderName, \\\"aggdistancelocal$(secs, nsecs, x, y, z)\\\" AS Distance\\nFROM \\\"${source}-odomDist\\\"\\nWHERE senderName='${senderName}'\",\"queryType\":\"sql\"},\"settings\":{\"contextParameters\":[],\"format\":\"long\"}}",
     "settings": {
      "contextParameters": [],
      "format": "long"
     }
    }
   ]
  },
  {
   "title": "Wifi Strenght over TIme",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "builder": {
      "query": "SELECT __time, senderName, wifiAvg\nFROM \"${source}-wifiData\"\nWHERE senderName='${senderName}' AND __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT __time, senderName, wifiAvg\\nFROM \\\"${source}-wifiData\\\"\\nWHERE senderName='${senderName}' AND __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY\",\"queryType\":\"sql\"},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Wifi strength by location",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "aggregation": "Sum",
     "alias": "A",
     "builder": {
      "query": "SELECT __time, location, \"avg(wifiAvg)\" AS \"AVG\",  \"min(wifiAvg)\" AS \"MIN\", \"max(wifiAvg)\" AS \"MAX\", senderName\nFROM \"${source}-wifiStats\"\nWHERE senderName='${senderName}'",
      "queryType": "sql"
     },
     "crit": -80,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "{\"builder\":{\"query\":\"SELECT __time, location, \\\"avg(wifiAvg)\\\" AS \\\"AVG\\\",  \\\"min(wifiAvg)\\\" AS \\\"MIN\\\", \\\"max(wifiAvg)\\\" AS \\\"MAX\\\", senderName\\nFROM \\\"${source}-wifiStats\\\"\\nWHERE senderName='${senderName}'\",\"queryType\":\"sql\"},\"settings\":{}}",
     "group": { "alias": "location", "name": "Status Checks", "url": "" },
     "units": "dB",
     "valueHandler": "Number Threshold",
     "warn": -60
    }
   ]
  },
  {
   "title": "Max Wifi Strenght",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "builder": {
      "query": "SELECT __time, \"max(wifiAvg)\", senderName\nFROM \"${source}-wifiStats\"\nWHERE __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY AND senderName='${senderName}'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT __time, \\\"max(wifiAvg)\\\", senderName\\nFROM \\\"${source}-wifiStats\\\"\\nWHERE __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY AND senderName='${senderName}'\",\"queryType\":\"sql\"},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Average Wifi Strenght",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "builder": {
      "query": "SELECT __time, \"avg(wifiAvg)\", senderName\nFROM \"${source}-wifiStats\"\nWHERE __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY AND senderName='${senderName}'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT __time, \\\"avg(wifiAvg)\\\", senderName\\nFROM \\\"${source}-wifiStats\\\"\\nWHERE __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY AND senderName='${senderName}'\",\"queryType\":\"sql\"},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Min Wifi Strenght",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "builder": {
      "query": "SELECT __time, \"min(wifiAvg)\", senderName\nFROM \"${source}-wifiStats\"\nWHERE __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY AND senderName='${senderName}'",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"query\":\"SELECT __time, \\\"min(wifiAvg)\\\", senderName\\nFROM \\\"${source}-wifiStats\\\"\\nWHERE __time >= CURRENT_TIMESTAMP - INTERVAL '30' DAY AND senderName='${senderName}'\",\"queryType\":\"sql\"},\"settings\":{}}"
    }
   ]
  }
 ]
}