version: '3.8'
services:
    zookeeper-01:
        image: zookeeper:3.6
        hostname: zookeeper-01
        restart: always
        ports:
            - 2181:2181
            - 8080:8090
        networks:
            - lamdba
        volumes:
            - type: bind
              source: F:\Docker Data\Image\Volumes
              target: /conf
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888
            
networks:
    lamdba:
        name: lamdba-network
        driver: bridge
        
volumes:
    zookeeper-conf: