version: "3.7"

services:
##### Monitoring
    portainer:
        image: portainer/portainer
        command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
        ports: 
            - target: 9000
              published: 8010
              mode: ingress
            - target: 8000
              published: 8020
              mode: ingress
        networks:
            - portainer-network
        volumes: 
            - type: volume
              source: portainer-persistence
              target: /data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

    portainer-agent:
        image: portainer/agent
        networks:
            - portainer-network
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
            - type: bind
              source: /var/lib/docker/volumes
              target: /var/lib/docker/volumes
        deploy:
            mode: global
            placement:
                constraints: [node.platform.os == linux]      

networks:
    portainer-network:
        name: portainer-network

volumes:
    portainer-persistence: