version: "3.8"

services:
#    grafana:
#        image: grafana/grafana:7.1.1
#        hostname: grafana
#        networks:
#            - dashboard-network
#        ports:
#            - target: 3000
#              published: 3000
#              mode: ingress
#        environment:
#            GF_INSTALL_PLUGINS: "grafana-clock-panel,abhisant-druid-datasource" 
#        deploy:
#            mode: replicated
#            replicas: 1
#            placement:
#                constraints: [node.role == manager]  # No need to be on the manager (node.hostname == ???                       


    SuperSet:
        image: amancevice/superset
        hostname: superset 
        networks:
            - dashboard-network
        ports:
            - target: 8080
              published: 3000
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]  # No need to be on the manager (node.hostname == ???                       

networks:
    dashboard-network:
        name: dashboard-network