version: "3.8"

services:
    postgres:
        image: postgres:latest
        hostname: postgres
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: volume
              source: metadata_data
              target: /var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=druid
            - POSTGRES_USER=druid
            - POSTGRES_DB=druid

    zookeeper:
        image: bitnami/zookeeper:3.6.1
        hostname: zookeeper
        restart: unless-stopped
        networks:
            - lambda-network
        volumes: 
            - type: volume
              source: zookeeper_data
              target: /bitnami/zookeeper/ 
        environment:
            ZOO_PORT_NUMBER: 2181
            ZOO_SERVER_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888
            ZOO_ENABLE_AUTH: "yes"
            ZOO_CLIENT_USER: druid
            ZOO_CLIENT_PASSWORD: druid
            ZOO_LOG_LEVEL: DEBUG

    coordinator:
        image: apache/druid:0.20.2
        hostname: coordinator
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: bind
              source: ./storage
              target: /opt/data
            - type: volume
              source: coordinator_var
              target: /opt/druid/var
        ports:
            - target: 8081
              published: 5000
        command:
            - coordinator
            - -Xms4500m
            - -Xmx4500m
            - -XX:+ExitOnOutOfMemoryError
            - -XX:+UseG1GC
            - -Duser.timezone=UTC
            - -Dfile.encoding=UTF-8
            - -Djava.io.tmpdir=var/tmp
            - -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
            - -Dderby.stream.error.file=var/druid/derby.log
            - -druid.service=druid/coordinator
            - -druid.plaintextPort=8081
            - -druid.coordinator.startDelay=PT10S
            - -druid.coordinator.period=PT5S
            - -druid.coordinator.asOverlord.enabled=true
            - -druid.coordinator.asOverlord.overlordService=druid/overlord
            - -druid.indexer.queue.startDelay=PT5S
            - -druid.indexer.runner.type=remote
            - -druid.indexer.storage.type=metadata
        env_file: 
            - druid.env

    broker:
        image: apache/druid:0.20.2
        hostname: broker
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: volume
              source: broker_var
              target: /opt/druid/var
        ports:
            - target: 8082
              published: 5100
        command:
            - broker
            - -Xms4g
            - -Xmx4g
            - -XX:MaxDirectMemorySize=3g
            - -XX:+ExitOnOutOfMemoryError
            - -XX:+UseG1GC
            - -Duser.timezone=UTC
            - -Dfile.encoding=UTF-8
            - -Djava.io.tmpdir=var/tmp
            - -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
            - -druid.service=druid/broker
            - -druid.plaintextPort=8082
            - -druid.server.http.numThreads=50
            - -druid.broker.http.numConnections=40
            - druid.broker.http.maxQueuedBytes=5MiB
            - -druid.processing.buffer.sizeBytes=500MiB
            - -druid.processing.numMergeBuffers=2
            - -druid.processing.numThreads=1
            - -druid.broker.cache.useCache=false
            - -druid.broker.cache.populateCache=false
        env_file:
            - druid.env

    router:
        image: apache/druid:0.20.2
        hostname: router
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: volume
              source: router_var
              target: /opt/druid/var
        ports:
            - target: 8888
              published: 5200
        command:
            - router
            - -Xms512m
            - -Xmx512m
            - -XX:+UseG1GC
            - -XX:MaxDirectMemorySize=128m
            - -XX:+ExitOnOutOfMemoryError
            - -XX:+UseG1GC
            - -Duser.timezone=UTC
            - -Dfile.encoding=UTF-8
            - -Djava.io.tmpdir=var/tmp
            - -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
            - -druid.service=druid/router
            - -druid.plaintextPort=8888
            - -druid.router.http.numConnections=50
            - -druid.router.http.readTimeout=PT5M
            - -druid.router.http.numMaxThreads=100
            - -druid.server.http.numThreads=100
            - -druid.router.defaultBrokerServiceName=druid/broker
            - -druid.router.coordinatorServiceName=druid/coordinator
            - -druid.router.managementProxy.enabled=true
        env_file:
            - druid.env
        
    middlemanager:
        image: apache/druid:0.20.2
        hostname: middlemanager
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: bind
              source: ./storage
              target: /opt/data
            - type: volume
              source: middle_var
              target: /opt/druid/var
        ports:
            - target: 8091
              published: 5300
        command:
            - middleManager
            - -Xms128m
            - -Xmx128m
            - -XX:+ExitOnOutOfMemoryError
            - -XX:+UseG1GC
            - -Duser.timezone=UTC
            - -Dfile.encoding=UTF-8
            - -Djava.io.tmpdir=var/tmp
            - -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
            - -druid.service=druid/middleManager
            - -druid.plaintextPort=8091
            - -druid.worker.capacity=3
            - -druid.server.http.numThreads=50
            - -druid.indexer.fork.property.druid.processing.numMergeBuffers=2
            - -druid.indexer.fork.property.druid.processing.buffer.sizeBytes=100MiB
            - -druid.indexer.fork.property.druid.processing.numThreads=1
        env_file:
            - druid.env

    historical:
        image: apache/druid:0.20.2
        hostname: historical
        restart: unless-stopped
        networks:
            - lambda-network
        volumes:
            - type: bind
              source: ./storage
              target: /opt/data
            - type: volume 
              source: historical_var
              target: /opt/druid/var
        ports:
            - target: 8083
              published: 5400
        command:
            - historical
            - -Xms4g
            - -Xmx4g
            - -XX:MaxDirectMemorySize=8g
            - -XX:+ExitOnOutOfMemoryError
            - -XX:+UseG1GC
            - -Duser.timezone=UTC
            - -Dfile.encoding=UTF-8
            - -Djava.io.tmpdir=var/tmp
            - -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
            - -druid.service=druid/historical
            - -druid.plaintextPort=8083
            - -druid.server.http.numThreads=50
            - -druid.processing.buffer.sizeBytes=500MiB
            - -druid.processing.numMergeBuffers=2
            - -druid.processing.numThreads=7
            - -druid.historical.cache.useCache=true
            - -druid.historical.cache.populateCache=true
            - -druid.cache.type=caffeine
            - -druid.cache.sizeInBytes=256MiB
        env_file:
           - druid.env

networks:
    lambda-network:
        name: lambda-network

volumes:
    metadata_data:
    zookeeper_data:
    coordinator_var:
    historical_var:
    broker_var:
    router_var:
    middle_var:
