version: "3.8"

services:
    postgres:
        image: postgres:latest
        hostname: postgres
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: volume
              source: metadata_data
              target: /var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=druid
            - POSTGRES_USER=druid
            - POSTGRES_DB=druid

    zookeeper:
        image: bitnami/zookeeper:3.6.1
        hostname: zookeeper
        restart: unless-stopped
        networks:
            - lambda-network
        volumes: 
            - type: volume
              source: zookeeper_data
              target: /bitnami/zookeeper/ 
        environment:
            ZOO_PORT_NUMBER: 2181
            ZOO_SERVER_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888
            ZOO_ENABLE_AUTH: "yes"
            ZOO_CLIENT_USER: druid
            ZOO_CLIENT_PASSWORD: druid
            ZOO_LOG_LEVEL: DEBUG

    coordinator:
        image: apache/druid:0.20.2
        hostname: coordinator
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: bind
              source: ./storage
              target: /opt/data
            - type: volume
              source: coordinator_var
              target: /opt/druid/var
        ports:
            - target: 8081
              published: 5000
        command:
            - coordinator
        env_file: 
            - druid.env

    broker:
        image: apache/druid:0.20.2
        hostname: broker
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: volume
              source: broker_var
              target: /opt/druid/var
        ports:
            - target: 8082
              published: 5100
        command:
            - broker
        env_file:
            - druid.env

    router:
        image: apache/druid:0.20.2
        hostname: router
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: volume
              source: router_var
              target: /opt/druid/var
        ports:
            - target: 8888
              published: 5200
        command:
            - router
        env_file:
            - druid.env
        
    middlemanager:
        image: apache/druid:0.20.2
        hostname: middlemanager
        restart: unless-stopped
        networks: 
            - lambda-network
        volumes:
            - type: bind
              source: ./storage
              target: /opt/data
            - type: volume
              source: middle_var
              target: /opt/druid/var
        ports:
            - target: 8091
              published: 5300
        command:
            - middleManager
        env_file:
            - druid.env

    historical:
        image: apache/druid:0.20.2
        hostname: historical
        restart: unless-stopped
        networks:
            - lambda-network
        volumes:
            - type: bind
              source: ./storage
              target: /opt/data
            - type: volume 
              source: historical_var
              target: /opt/druid/var
        ports:
            - target: 8083
              published: 5400
        command:
            - historical
        env_file:
           - druid.env

networks:
    lambda-network:
        name: lambda-network

volumes:
    metadata_data:
    zookeeper_data:
    coordinator_var:
    historical_var:
    broker_var:
    router_var:
    middle_var:
